project:
  type: website
  output-dir: docs

website:
  title: "Janelia Data Standards"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - pages/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



